version: "3.8"

services:
  search-inference:
    image: registry.melior.ai/semantic-search:latest
    networks:
      - "semantic-search-network"
    ports:
      - "9400:9400"
    volumes:
      - "$PWD/semsearch:/app/mount"
    command:
      - inference-server
      - -c
      - /app/mount/config.yml
    environment:
      - LOG_LEVEL=INFO
    depends_on:
      - mongo
      - textual-encoders


  search-indexer:
    image: registry.melior.ai/semantic-search:latest
    networks:
      - "semantic-search-network"
    volumes:
      - "$PWD/data:/app/mount/data"
      - "$PWD/semsearch:/app/mount"
    command:
      - index
      - -c
      - /app/mount/config.yml
    environment:
      - LOG_LEVEL=INFO
    depends_on:
      - mongo
      - ticketer
      - textual-encoders

  ticketer:
    image: registry.melior.ai/ticketer:latest
    # network_mode: "host"
    networks:
      - "semantic-search-network"
    ports:
      - "7508:7508"
    command:
      - --port
      - "7508"
      - --debug
    environment:
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  textual-encoders:
    # image: registry.melior.ai/textual-encoders-cpu:0.10.1
    image: registry.melior.ai/textual-encoders-cuda:0.8.3
    runtime: nvidia
    networks:
      - "semantic-search-network"
    scale: 2
    expose:
      - "9600"
    command:
      - -e
      - msmarco-distilbert-base-v2
      - --model-dir
      - /app/mount/models
      - -vv
    volumes:
      - "./semsearch/models/:/app/mount/models"
    environment:
      - LOG_LEVEL=DEBUG
    depends_on:
      - nginx

  redis:
    image: redis
    # network_mode: "host"
    networks:
      - "semantic-search-network"
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --protected-mode
      - "no"

  nginx:
    image: nginx:latest
    networks:
      - "semantic-search-network"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"

  mongo:
    image: mongo:latest
    # network_mode: "host"
    networks:
      - mongo-network
      - semantic-search-network
    ports:
      - "27017:27017"


networks:
  semantic-search-network: {}
  mongo-network: {}
